apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend
  labels:
    app: {{ .Release.Name }}-backend
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-backend
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-backend
    spec:
    {{- if .Values.imagePullSecret }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecret }}
    {{- end }}
      containers:
      - name: backend
        image: {{ .Values.backend.image | quote}}
        imagePullPolicy: {{ .Values.backend.imagePullPolicy }}
        ports:
          - name: http
            containerPort: {{ .Values.backend.containerPort }}
        envFrom:
          - configMapRef:
              name: {{ .Release.Name }}-backend-config
          - secretRef:
              name: {{ .Values.backend.secretName }}
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
