apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-frontend
  labels:
    app: {{ .Release.Name }}-frontend
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-frontend
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-frontend
    spec:
    {{- if .Values.imagePullSecret }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecret }}
    {{- end }}
      containers:
        - name: frontend
          image: {{ .Values.frontend.image | quote }}
          imagePullPolicy: {{ .Values.frontend.imagePullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.frontend.containerPort }}
