apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-postgresql
spec:
  serviceName: {{ .Release.Name }}-postgresql
  replicas: {{ .Values.postgresql.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-postgresql
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-postgresql
    spec:
      containers:
        - name: postgresql
          image: {{ .Values.postgresql.image | quote }}
          imagePullPolicy: {{ .Values.postgresql.imagePullPolicy }}
          ports:
            - name: postgresql
              containerPort: {{ .Values.postgresql.containerPort }}
          envFrom:
            - secretRef:
                name: {{ .Values.postgresql.secretName }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.postgresql.storage.size }}