apiVersion: apps/v1
kind: Deployment
metadata:
  name: k3s-api-deployment
  labels:
    app: k3s-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k3s-api
  template:
    metadata:
      labels:
        app: k3s-api
    spec:
      containers:
        - name: k3s-api
          image: ghcr.io/newjeansbubble/k3s-basic-app-backend:latest
          ports:
          - containerPort: 3000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: k3s-api-secret
                  key: DATABASE_URL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: k3s-api-secret
                  key: JWT_SECRET
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: k3s-api-config
                  key: PORT
            - name: APP_ENV
              valueFrom:
                configMapKeyRef:
                  name: k3s-api-config
                  key: APP_ENV          
            - name: APP_VERSION
              valueFrom:
                configMapKeyRef:
                  name: k3s-api-config
                  key: APP_VERSION 
            - name: CORS_ORIGIN
              valueFrom:
                configMapKeyRef:
                  name: k3s-api-config
                  key: CORS_ORIGIN 