backend:
  image: ghcr.io/newjeansbubble/k3s-basic-app-backend:1.2.0
  imagePullPolicy: IfNotPresent

  config:
    corsOrigin: "http://k3s-basic-app.k8s.orb.local"
    appEnv: "local"

frontend:
  image: ghcr.io/newjeansbubble/k3s-basic-app-frontend:1.2.0
  imagePullPolicy: IfNotPresent

  ingress:
    className: traefik
    host: k3s-basic-app.k8s.orb.local